<a href="https://colab.research.google.com/github/mariyasevidhasnowlin16-art/Titanic-Dataset/blob/main/Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
file_path ="/content/drive/MyDrive/Titanic-Dataset.csv"

In [4]:
data=pd.read_csv(file_path)

In [5]:
data=pd.read_csv(file_path)

In [6]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/Titanic-Dataset.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:

age_series = data["Age"]
fare_series = data["Fare"]
survival_series = data["Survived"]

print(type(age_series))
print(type(data))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [11]:
data.head()
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [13]:
data.isnull().sum()

data["Age"].fillna(data["Age"].mean(), inplace=True)

data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)
data.dropna(inplace=True)

/tmp/ipykernel_190/1832611075.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].mean(), inplace=True)
/tmp/ipykernel_190/1832611075.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)

In [14]:
data.loc[0]
data.loc[0, "Name"]

KeyError: 0

In [15]:
data.iloc[0:5]
data.iloc[:, 2:5]

     Pclass                                               Name     Sex
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
6         1                            McCarthy, Mr. Timothy J    male
10        3                    Sandstrom, Miss. Marguerite Rut  female
11        1                           Bonnell, Miss. Elizabeth  female
..      ...                                                ...     ...
871       1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female
872       1                           Carlsson, Mr. Frans Olof    male
879       1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female
887       1                       Graham, Miss. Margaret Edith  female
889       1                              Behr, Mr. Karl Howell    male

[204 rows x 3 columns]

In [16]:
data.rename(columns={"Sex": "Gender"}, inplace=True)

In [18]:
pivot_table = data .pivot_table(values="Survived",
                             index="Gender",
                             columns="Pclass",
                             aggfunc="mean")
print(pivot_table)

Pclass         1         2         3
Gender
female  0.962963  0.900000  0.666667
male    0.410526  0.666667  0.333333

In [19]:
data[data["Age"] > 30]

data[data["Fare"] > 50]

data[(data["Gender"] == "female") & (data["Survived"] == 1)]
data.sort_values(by="Fare", ascending=False)
data.sort_values(by="Age")
data.sort_values(by="Survived")

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,E46,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.000000,3,2,19950,263.0000,C23 C25 C27,S
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.000000,1,0,36973,83.4750,C83,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.000000,0,1,113509,61.9792,B30,C
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.000000,0,0,348123,7.6500,F G73,S
...,...,...,...,...,...,...,...,...,...,...,...,...
839,840,1,1,"Marechal, Mr. Pierre",male,29.699118,0,0,11774,29.7000,C47,C
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.000000,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.000000,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C

In [20]:
data.groupby("Gender")["Survived"].mean()
data.groupby("Pclass")["Age"].mean()
data.groupby("Embarked")["Survived"].sum()

Embarked
C    52
Q     2
S    82
Name: Survived, dtype: int64

In [21]:
class_info = pd.DataFrame({
    "Pclass": [1, 2, 3],
    "Class_Name": ["First", "Second", "Third"]
})
merged_data = pd.merge(data, class_info, on="Pclass")
combined = pd.concat([data.head(), data.tail()])

In [22]:
data.groupby("Survived")["Age"].mean()
data["Fare"].max()
data["Fare"].min()
survival_rate = data["Survived"].mean() * 100
print("Survival Percentage:", survival_rate)

Survival Percentage: 66.66666666666666